name: Russell Matney
markdown: redcarpet
highlighter: true
subhead: web and ios apps. fiction and writing.
future: false
permalink: none
author: Russell Matney

url: http://russmatney.com/
description: "Web tech and other things in code"
