(ns blog.generate
  (:require
   [blog.log :as log]
   [babashka.fs :as fs]))

(def generated-page-preamble
  "<!--- HELLO WORLD!!! \n  this page was GENERATED by some tasks.clj!\n  so-mind-ya-bizniz. --->\n\n")

(defn write-page
  [{directory  :directory
    path       :path
    preamble   :preamble
    content    :content
    overwrite? :overwrite?
    :as        _def
    :or        {overwrite? false}
    }]
  (let [path (str directory "/" path)]
    (fs/create-dirs (fs/parent path)) ;; mkdir -p path
    (if (and (fs/exists? path) (not overwrite?))
      (log/log "Skipping overwrite of existing file! pass :overwrite? true to replace")
      (do
        (log/log "Writing to" path)
        (spit path
              (str generated-page-preamble "\n\n"
                   (when preamble (str preamble "\n\n"))
                   content))))))

(comment
  (write-page
    {:directory  (str (fs/home) "/russmatney")
     :path       "some-file.md"
     :content    "### hi there"
     :overwrite? true}))
