(ns blog.generate
  (:require
   [blog.log :as log]
   [babashka.fs :as fs]))

(def generated-page-preamble
  "<!--- HELLO WORLD!!! \n  this page was GENERATED by some tasks.clj!\n  so-mind-ya-bizniz. --->\n\n")

(defn write-page
  [{directory :directory
    path      :path
    preamble  :preamble
    content   :content
    :as       def}]
  (let [path (str directory "/" path)]
    (log/log "Writing to" path)
    (fs/create-dirs (fs/parent path)) ;; mkdir -p path
    (spit path
          (str generated-page-preamble "\n\n"
               (when preamble (str preamble "\n\n"))
               content))))

(comment
  (write-page
    {:directory (str (fs/home) "/russmatney")
     :path      "some-file.md"
     :content   "### hi there"}))
