(ns blog.generate
  (:require
   [blog.log :as log]))

(def generated-page-preamble
  "<!--- HELLO WORLD!!! \n  this page was GENERATED by some tasks.clj!\n  so-mind-ya-bizniz. --->\n\n")

(defn write-page
  [{directory :directory
    path      :path
    preamble  :preamble
    content   :content
    :as       def}]
  (let [path (str directory "/" path)]
    (log/log "Writing to" path)
    (spit path
          (str generated-page-preamble "\n\n"
               (when preamble (str preamble "\n\n"))
               content))))
