(ns blog.pages
  (:require
   [clojure.string :as string]

   [blog.log :as log]
   [blog.config :as config]
   [blog.post :as post]
   [blog.markdown :as md]
   [blog.generate :as gen]
   ))

;; vars/static data

(def sidebar-top-links
  "
* [Home](/)
* [About](/about.md)
* [Dev Logs](/devlogs/)
* [Portfolio](/portfolio/)
* [Posts](/posts/)")


(def sidebar-top-links-with-post-categories
  (str
    sidebar-top-links
    "
  * [100 word stories](/posts/100-worders/)
  * [Techsposure](/posts/techsposure/)
  * [Get It Write](/posts/getitwrite/)
  * [Groks](/posts/groks/)
  * [Notes](/posts/notes/)
"))

(defn h1-text-link [post]
  (str "* " (md/post->md-text-link post)))

(defn write-sidebar
  [{:as def title :title}]
  (let [def (cond-> def
              (nil? (:->text def))
              (assoc :->text h1-text-link))]
    (cond-> def
      true
      (assoc :path "_sidebar.md")

      (nil? (:preamble def))
      (assoc :preamble
             (str sidebar-top-links
                  (when title (str "\n\n--\n\n" title "\n\n"))))

      (nil? (:content def))
      (assoc :content (md/posts-index def))

      true
      (assoc :overwrite? true)

      true
      (gen/write-page))))

(defn write-index
  [{:as def title :title}]
  (let [def (cond-> def
              (nil? (:->text def))
              (assoc :->text h1-text-link))]
    (cond-> def
      true
      (assoc :path "README.md")

      (nil? (:content def))
      (assoc :content (md/posts-index def))

      (nil? (:preamble def))
      (assoc :preamble (str "## " (or title " More Posts")))

      true
      (assoc :overwrite? true)

      true
      (gen/write-page))))


;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; TODO add malli schemas to these page defs
;; page defs

;; helpers

(defn text-post-tags [post]
  (cond
    (string/includes? (:post/fname post) "gloss") " #glossolalia"
    (#{"techsposure"} (:post/parent-fname post))  " #techsposure"
    (#{"getitwrite"} (:post/parent-fname post))   " #getitwrite"
    (#{"groks"} (:post/parent-fname post))        " #groks"
    (#{"100-worders"} (:post/parent-fname post))  " #hundos"))

(defn post->text-with-tags [post]
  (str "* " (md/post->md-text-link post)
       (text-post-tags post)))

;; devlogs

(def devlog-page-defs
  ;; page defs are generated by passing the full map to the `:generate` function
  {:devlogs/sidebar
   {:generate      write-sidebar
    :directory     config/devlogs-dir
    :title         "Dev Logs"
    :->text        post->text-with-tags
    :skip-group-by true}

   :devlogs/index
   {:generate      write-index
    :directory     config/devlogs-dir
    :title         "Dev Logs"
    :->text        post->text-with-tags
    :skip-group-by true
    ;; TODO we could slurp-in the preamble, maybe up to a <!--- BLOG END PREAMBLE ---> comment?
    :preamble      (str "
## Dev Logs

Notes, clips, commits, etc collected along the dev path.
")}})


(def posts-page-defs
  {:posts/index
   {:generate  write-index
    :directory config/posts-dir
    :title     "Posts"
    :->posts   post/local-posts
    :->text    post->text-with-tags
    :preamble  (str "

## Posts

Blog posts from over the years.

Some broad categories:

* [100 word stories](/posts/100-worders/)
* [Get It Write](/posts/getitwrite/)
* [groks](/posts/groks/)
* [techsposure](/posts/techsposure/)

## Everything

> By month

")}})

(def hundos-page-defs
  {:hundos/sidebar
   {:generate  write-sidebar
    :directory config/hundos-dir
    :preamble  sidebar-top-links-with-post-categories}

   :hundos/index
   {:generate  write-index
    :directory config/hundos-dir
    :preamble  (str "
## 100 Word Stories

Known colloquially as hundos.
")}})

(def techsposure-page-defs
  {:techsposure/sidebar
   {:generate  write-sidebar
    :directory config/techsposure-dir
    :title     "Techsposure"
    :preamble  sidebar-top-links-with-post-categories}

   :techsposure/index
   {:generate  write-index
    :directory config/techsposure-dir
    :title     "Techsposure"}})

(def getitwrite-page-defs
  {
   :getitwrite/sidebar
   {:generate  write-sidebar
    :directory config/getitwrite-dir
    :title     "Get It? Write!"
    :preamble  sidebar-top-links-with-post-categories
    }

   :getitwrite/index
   {:generate  write-index
    :directory config/getitwrite-dir
    :title     "Get It? Write!"
    }})

(def groks-page-defs
  {:groks/sidebar
   {:generate  write-sidebar
    :directory config/groks-dir
    :title     "GROKs"
    :preamble  sidebar-top-links-with-post-categories}

   :groks/index
   {:generate  write-index
    :directory config/groks-dir
    :title     "GROKs"
    :preamble  (str "
## GROKs

Notes and hopefully specific things I'm trying to understand better.
")}})

(def notes-page-defs
  {:notes/sidebar
   {:generate  write-sidebar
    :directory config/garden-posts-dir
    :title     "Notes"
    :preamble  sidebar-top-links-with-post-categories}

   :notes/index
   {:generate  write-index
    :directory config/garden-posts-dir
    :title     "Notes"
    :preamble  (str "
## Garden Notes

This section is still a work in progress!

I have a years-deep mindgarden of interconnected notes,
and I'm toying with different ways of sharing that content here.

To start it'll probably be some listicles.

I hope to take time with each,
rather than throw them all over the wall.

")}})

(defn all-page-defs []
  (merge devlog-page-defs
         posts-page-defs
         hundos-page-defs
         techsposure-page-defs
         getitwrite-page-defs
         groks-page-defs
         notes-page-defs
         ))

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; generators

(defn def->generate-page [def]
  (log/log "Generating page for def" (:id def))
  (let [def    (cond-> def
                 ;; attach list of posts
                 (:->posts def)
                 (assoc :posts ((:->posts def))))
        gen-fn (:generate def)]
    (gen-fn def)))

(defn write-indexes-and-sidebars []
  (->> (all-page-defs)
       (map (fn [[id def]]
              (let [def (assoc def :id id)]
                (if-not (:generate def)
                  (log/log "WARN no :generate on def" id)
                  (def->generate-page def)))))
       (doall)))

(comment
  (-> (:groks/index groks-page-defs)
      (def->generate-page))

  (-> (:posts/index posts-page-defs)
      (def->generate-page))

  (write-indexes-and-sidebars))
